{"name": "test_auth_success", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = <Response [403]>.ok", "trace": "self = <test_auth_api.TestAuthAPI object at 0x104a38640>\n\n    def test_auth_success(self):\n        \"\"\"Test successful authentication\"\"\"\n        response = self.client.post(\n            f\"{self.client.base_url}{BASE_PATH}\",\n            json={\"username\": \"admin\", \"password\": \"password123\"}\n        )\n>       assert response.ok\nE       assert False\nE        +  where False = <Response [403]>.ok\n\ntests/test_auth_api.py:18: AssertionError"}, "description": "Test successful authentication", "start": 1750257936758, "stop": 1750257936971, "uuid": "e2067522-8a54-4c4f-bdd4-ac975eacb46b", "historyId": "965543a3ad27117d78ad9591a55f5cd5", "testCaseId": "965543a3ad27117d78ad9591a55f5cd5", "fullName": "tests.test_auth_api.TestAuthAPI#test_auth_success", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth_api"}, {"name": "subSuite", "value": "TestAuthAPI"}, {"name": "host", "value": "Rs-MacBook-Pro-2.local"}, {"name": "thread", "value": "56688-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth_api"}]}